CREATE DATABASE cicerone;


CREATE TABLE tbl_usuario(
	cod_usuario INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	nome VARCHAR(100) NOT NULL,
	rg VARCHAR(9) NOT NULL UNIQUE,
	cpf VARCHAR(11) NOT NULL UNIQUE,
	endereco VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL UNIQUE,
	telefone VARCHAR(15) NOT NULL UNIQUE,
	nivel VARCHAR(15),
	estatus VARCHAR(15),
	PRIMARY KEY (cod_usuario)
)  ENGINE = MYISAM;


SELECT * FROM tbl_usuario;